name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true
  FORCE_COLOR: 3

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Biome
      uses: biomejs/setup-biome@v2

    - name: Run Biome
      run: biome ci

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Run tests
      run: bun test --coverage --coverage-reporter=lcov

    - name: Upload coverage
      if: always()
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: coverage/lcov.*.info
        minimum-coverage: 80
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true
